version: '3.8'

services:
  # Development Database only
  database:
    image: postgres:16-alpine
    container_name: prototype-db-dev
    environment:
      POSTGRES_DB: prototype
      POSTGRES_USER: prototype
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prototype"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - prototype-network

volumes:
  postgres_dev_data:

networks:
  prototype-network:
    driver: bridge
